#!/bin/sh
cd $(dirname $0)
for dotfile in .?*
do
    if [ $dotfile != '..' ] && [ $dotfile != '.git' ]
    then
        name=`echo $dotfile | sed -e "s/-/\//"`
        name=`echo $name | sed -e "s/+/-/"`
        ln -fs "$PWD/$dotfile" "$HOME/$name"
    fi
done

ln -fs "$PWD/Brewfile" "$HOME/Brewfile"
