#!/bin/sh
cd $(dirname $0)

for dotfile in .?*
do
  if [ $dotfile != '..' ] && [ $dotfile != '.git' ]
  then
    name=`echo $dotfile | sed -e "s/-/\//"`
    name=`echo $name | sed -e "s/+/-/"`
    ln -fsn "$PWD/$dotfile" "$HOME/$name"
  fi
done

# disable override
if [ -e "$HOME/.zsh.d/config/override" ]; then
  rm $HOME/.zsh.d/config/override
fi

for brewfile in Brewfile*
do
  ln -fs "$PWD/$brewfile" "$HOME/$brewfile"
done

curl https://raw.githubusercontent.com/Shougo/neobundle.vim/master/bin/install.sh | sh

source ~/.zshrc

go_setup

brew install zsh
brew install ghq
brew install hub
brew install direnv

# Font Install
if [ `uname -s` == 'Darwin' ]; then
  if [ ! -e "$HOME/Library/Fonts/Consolas for Powerline.ttf" ]; then
    wget https://dl.dropboxusercontent.com/u/34772227/fonts.zip -O /tmp/fonts.zip
    unzip -o /tmp/fonts.zip -d /tmp/
    cp -vf /tmp/fonts/*.otf $HOME/Library/Fonts/
    cp -vf /tmp/fonts/*.ttf $HOME/Library/Fonts/
  fi
fi
