for config_file in ~/.zsh.d/config/*.zsh
do
  source "$config_file"
done

if [ -e $HOME/.zsh.d/config/override/ ]; then
  for config_file in ~/.zsh.d/config/override/*.zsh
  do
    source "$config_file"
  done
fi
